services:
  postgres:
    image: postgres:15-alpine
    container_name: family_dashboard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped

volumes:
  postgres_data:
    name: family_dashboard_postgres_data 