"""Create finance tables

Revision ID: 9244da05a26f
Revises: bc0954cfd86f
Create Date: 2025-05-19 12:26:55.841344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9244da05a26f'
down_revision = 'bc0954cfd86f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 