"""Rename finance tables

Revision ID: bc0954cfd86f
Revises: ce90a9ad24b7
Create Date: 2025-05-19 12:17:22.930300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0954cfd86f'
down_revision = 'ce90a9ad24b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'description')
    # ### end Alembic commands ### 