"""Add finance tables

Revision ID: ce90a9ad24b7
Revises: ce6a893fa650
Create Date: 2025-05-19 12:14:43.143114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce90a9ad24b7'
down_revision = 'ce6a893fa650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 